# Change these first
owner: wirewayproject # Your GitHub organization or username, where this repository lives
repo: upptime

sites:
  - name: Proxy
    url: https://wireway.ch/api/status/nodes/?node=1
  - name: r-place.ch
    url: https://r-place.ch
  - name: Wireway Website
    url: https://wireway.ch
  - name: Wireway Autoajax
    url: https://autoajax.wireway.ch
  - name: Epilogue
    url: https://epilogue.social
    expectedStatusCodes:
      - 200
      - 403
  - name: Piped
    url: https://piped.wireway.ch
    expectedStatusCodes:
      - 200
      - 403

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 */2 * * *"
  summary: "0 */2 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */2 * * *"


status-website:
  cname: status.wireway.ch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wireway
  introTitle: "**Wireway** is a project operated by a single person making Websites"
  introMessage: Status page hosted by GitHub. Check out some of my projects at [wireway.ch](https://wireway.ch)
  navbar:
    - title: Status
      href: /
    - title: Wireway.ch
      href: https://wireway.ch
    - title: Speedtest
      href: https://speedtest.wireway.ch
